version: '3'

services:
  app:
    build: ./
    image: kb/demo
    expose:
      - 4040
    environment:
      NODE_ENV: production
      SERVER_PORT: 4040
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://192.168.31.76/mean1
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
