version: '3'

services:
  app:
    build: ./
    image: karthik/owndrive
    expose:
      - 4000
    environment:
      NODE_ENV: development
      SERVER_PORT: 80
      MONGO_HOST: mongodb://karthick4483:myOwnDrive0404@cluster0-shard-00-00-tiucb.mongodb.net:27017,cluster0-shard-00-01-tiucb.mongodb.net:27017,cluster0-shard-00-02-tiucb.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true
      MONGO_USERNAME: karthick4483
      MONGO_PASSWORD: myOwnDrive0404
      MEAN_FRONTEND: react
      SMPT_HOST: smtp.gmail.com
      SMPT_PORT: 587
      SMPT_EMAIL_ID: noreplyowndrive@gmail.com
      SMPT_EMAIL_PASSWORD: owndrivepp@4483
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
